recon/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('contractors.urls')),
    path('user/', include('users.urls')),
]

users/urls.py
from django.urls import path
from users import views

app_name = "users"
urlpatterns = [
    path('register', views.user_registration, name='user_register'),
    path('register/process', views.user_process, name='user_process'),
    path('dashboard', views.user_dashboard, name='user_dashboard'),
    path('add_project', views.add_project, name='user_add_project'),
    path('remove_project/<int:project_id>', views.remove_project, name="user_remove_project"),
    path('browse', views.contractor_list, name='contractors_list'),
    path('sort', views.sort, name='user_sort'),
]

users/models.py
from django.db import models
from datetime import datetime

import re
import bcrypt

# Create your models here.

class UserManager(models.Manager):
    def validator(self, postData, instance=None):
        errors = {}

        name_regex = re.compile(r'^[a-zA-Z]')
        email_regex = re.compile(r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$')

        if len(postData['fname']) < 2:
            errors['fname'] = "First Name is required and should be at least 2 characters."
            if not name_regex.match(postData['fname']):
                errors['fname'] = "First Name must have letters only."

        if len(postData['lname']) < 2:
            errors['lname'] = "Last Name is required and should be at least 2 characters."
            if not name_regex.match(postData['lname']):
                errors['lname'] = "Last Name must have letters only."

        if not email_regex.match(postData['email']):
            errors['email'] = "Please enter a valid email address."
        elif instance is None and self.filter(email=postData['email']).exists():
            errors['email'] = "Email is already in use."
        elif instance is not None and self.filter(email=postData['email']).exclude(id=instance.id).exists():
            errors['email'] = "Email is already in use."

        if len(postData['password']) < 8:
            errors['password'] = "Password should be at least 8 characters."

        if postData['password'] != postData['cpassword']:
            errors['cpassword'] = "Passwords do not match."

        return errors


class User(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.EmailField(max_length=255, unique=True)
    password = models.CharField(max_length=128)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

users/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from users.models import User
from contractors.models import Contractor
from contractors.models import Project

import bcrypt

# Create your views here.
def user_registration(request):
    return render(request,'userreg.html')

def user_process(request):
    if request.method == 'POST':
        errors = User.objects.validator(request.POST)
        email = request.POST['email']
        if Contractor.objects.filter(email=email).exists():
            errors['email'] = "Email is already in use."
        if len(errors) > 0:
            is_valid = False
            data = {
                'is_valid': is_valid,
                'errors': errors
            }
            return JsonResponse(data)
        
        else:
            first_name = request.POST['fname']
            last_name = request.POST['lname']
            email = request.POST['email']
            password = request.POST['password']
            pw_hash = bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()
            logged_user = User.objects.create(
                first_name = first_name,
                last_name = last_name,
                email = email,
                password = pw_hash,
            )
            request.session['user_id'] = logged_user.id
            is_valid = True
            data = {
                'is_valid': is_valid
            }
            return JsonResponse(data)
        
def user_dashboard(request):
    if 'user_id' in request.session:
        user = User.objects.get(id=request.session['user_id'])
        context = {
            'user': user,
            'projects': user.projects.all()
        }

        return render(request, 'userdash.html', context)
    else:
        return redirect('/')

def add_project(request):
    if 'user_id' in request.session:
        user = User.objects.get(id=request.session['user_id'])
        errors = {}
        if len(request.POST['project_code']) < 5:
            errors['project_code'] = "Please use a valid code."
            is_valid = False
            data = {
                'is_valid': is_valid,
                'errors': errors
                }
            return JsonResponse(data)
        else:
            project_code = request.POST['project_code']
            project = Project.objects.filter(project_code=project_code).first()
            is_valid = True
            if not project:
                errors['project_code'] = "No project with this code."
                is_valid = False
            if is_valid and user in project.owners.all():
                errors['project_code'] = "You already added this project."
            if len(errors) > 0:
                is_valid = False
                data = {
                    'is_valid': is_valid,
                    'errors': errors
                }
                return JsonResponse(data)
            else:
                project.owners.add(user)
                data = {
                    'is_valid': is_valid
                }
                return JsonResponse(data)
            
def remove_project(request, project_id):
    project = Project.objects.get(id=project_id)
    if 'user_id' in request.session:
        user = User.objects.get(id=request.session['user_id'])
        project.owners.remove(user)
        return redirect('/user/dashboard')
    
def contractor_list(request):
    if 'user_id' in request.session:
        user = User.objects.get(id=request.session['user_id'])
        all_contractors = Contractor.objects.all()
        if 'sort' in request.session:
            if request.session['sort'] == 1:
                all_contractors = Contractor.objects.all().order_by('company_name')
            elif request.session['sort'] == 2:
                all_contractors = Contractor.objects.all().order_by('specialization')
        else:
            request.session['sort'] = 0
        context = {
            'all_contractors': all_contractors,
            'user': user,
            'sort': request.session['sort']
        }
        del request.session['sort']
        return render(request, 'contractorlist.html', context)
    else:
        return redirect('/')
    
def sort(request):
    if 'user_id' in request.session:
        user = User.objects.get(id=request.session['user_id'])
        if request.POST['sort'] == "1":
            request.session['sort'] = 1
        elif request.POST['sort'] == "2":
            request.session['sort'] = 2
        return redirect('/user/browse')
    else:
        return redirect('/')

users/templates/contractorlist.html
{% load custom_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>reCon Contractor List</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg custom-navbar" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/user/dashboard">reCon</a>
            <span class="navbar-text">{{user.first_name}} {{user.last_name}}</span>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/user/dashboard">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active fw-bold" aria-current="page" href="/user/browse">Browse Contractors</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/logout">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- main content -->
    <div class="container-fluid mt-5 pb-5">
        <div class="d-flex align-items-center justify-content-between">
            <p class="h3">List of Contractors</p>
            <form action="/user/sort" method="POST">
                {% csrf_token %}
                <div class="d-flex">
                    <div>
                        <label class="form-label me-3 mt-1">Sort by:</label>
                    </div>
                    <div class="me-3">
                        <select class=" form-select-sm" name="sort">
                            <option {% if sort == 0 %}selected{% endif %}>----------</option>
                            <option value="1" {% if sort == 1 %}selected{% endif %}>Name</option>
                            <option value="2" {% if sort == 2 %}selected{% endif %}>Specialization</option>
                        </select>
                    </div>
                    <div>
                        <input type="submit" value="Go" class="btn btn-secondary btn-sm">
                    </div>
                </div>
            </form>
        </div>
            {% if not all_contractors %}
            <div class="border border-secondary rounded d-flex align-items-center justify-content-center" style="height: 300px;">
                <p>There are no registered contractors.</p>
            </div>
            {% else %}
            <div class="border border-2 border-secondary rounded border-warning">
                <table class="table table-hover align-middle border rounded overflow-hidden">
                    <thead>
                        <tr class="table-warning">
                            <th class="col-3">Name</th>
                            <th class="col-3">Specialization</th>
                            <th class="col-3">Description</th>
                            <th class="col-3 d-none d-sm-table-cell">Actions</th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        {% for contractor in all_contractors %}
                            <tr class="table-row-border" data-href="/contractor/projects/{{project.id}}">
                                <td><a href="/contractor/profile/{{contractor.id}}" class="text-decoration-none">{{contractor.company_name}}</a></td>
                                <td>{{contractor.specialization}}</td>
                                {% if not contractor.company_description%}
                                <td></td>
                                {% else %}
                                <td>{{contractor.company_description}}</td>
                                {% endif %}
                                <td class="d-none d-sm-table-cell">
                                    <a href="/contractor/profile/{{contractor.id}}"><button class="btn btn-primary btn-sm border">View Profile</button></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% endif %}
        <!-- <div class="my-3">
            <a href="/contractor/projects/create"><button class="btn btn-success">Create Project</button></a>
        </div> -->
    </div>
    <footer class="footer">
        <p>By Jorge Jason Joaquino</p>
    </footer>
    <script>
        $(document).ready(function() {
            $('#add').on('submit', function(e){
                e.preventDefault();

                var p_code = $('#p_code').val();

                $.ajax({
                    type:'POST',
                    url:'{% url "users:user_add_project" %}',
                    data: {
                        'project_code': p_code,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function(response){
                        console.log(response);
                        if(response.is_valid) {
                            window.location.href='/user/dashboard'
                        }
                        else {
                            if(response.errors.project_code) {
                                $('#code-error').empty()
                                var project_code_error = "<span style='color:red'>"+response.errors.project_code+"</span>"
                                $('#code-error').append(project_code_error)
                            }
                            else {
                                $('#code-error').empty()
                            }
                        }
                    }

                });
            });
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

users/templates/userdash.html
{% load custom_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>reCon Client Dashboard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg custom-navbar" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/user/dashboard">reCon</a>
            <span class="navbar-text">{{user.first_name}} {{user.last_name}}</span>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active fw-bold" aria-current="page" href="/user/dashboard">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/user/browse">Browse Contractors</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/logout">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- main content -->
    <div class="container-fluid mt-5 pb-5">
        <div>
            <p class="h3 mb-5">Current On-going Projects</p>
            <form id="add" action="/user/add_project" method="POST">
                {% csrf_token %}
                <div class="d-flex align-items-center mb-3">
                    <div class="me-3">
                        <label class="col-form-label fw-bold">Project Code:</label>
                    </div>
                    <div class="me-3">
                        <input type="text" id="p_code" name="project_code" class="form-control form-control-sm">
                    </div>
                    <div class="me-3">
                        <input class="form-control btn btn-success btn-sm" type="submit" value="Add Project">
                    </div>
                    <div class="" id="code-error"></div>
                </div>
            </form>
        </div>
            {% if not projects %}
            <div class="border border-secondary rounded d-flex align-items-center justify-content-center" style="height: 300px;">
                <p>You currently have no projects from Contractors.</p>
            </div>
            {% else %}
            <div class="table-responsive-md border border-2 border-warning rounded">
                    <table class="table table-hover align-middle border rounded overflow-hidden">
                        <thead class="table-warning">
                            <tr>
                                <th>Name</th>
                                <th>Contractor</th>
                                <th class="d-none d-sm-table-cell">Cost</th>
                                <th>Target Completion Date</th>
                                <th>Code</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            {% for project in projects %}
                                <tr class="table-row-border" data-href="/contractor/projects/{{project.id}}">
                                    <td><a href="/contractor/projects/{{project.id}}" class="text-decoration-none fw-bold">{{project.project_name}}</a></td>
                                    <td><a href=/contractor/profile/{{project.contractor.id}} class="text-decoration-none">{{project.contractor.company_name}}</a></td>
                                    <td class="d-none d-sm-table-cell">₱ {{project.project_cost|format_thousands_separator}}</td>
                                    <td>{{project.completion_date|date:"F j, Y"}}</td>
                                    <td>{{project.project_code}}</td>
                                    <td>
                                        <a href="/contractor/projects/{{project.id}}"><button class="btn btn-primary btn-sm border d-none d-md-inline-block">View</button></a>
                                        <a href="/user/remove_project/{{project.id}}" class="my-1"><button class="btn btn-primary btn-sm border" onclick="return confirm('Are you sure you want to remove this project from your list?')">Remove</button></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
            </div>
            {% endif %}
        <!-- <div class="my-3">
            <a href="/contractor/projects/create"><button class="btn btn-success">Create Project</button></a>
        </div> -->
    </div>
    <footer class="footer">
        <p>By Jorge Jason Joaquino</p>
    </footer>
    <script>
        $(document).ready(function() {
            $('#add').on('submit', function(e){
                e.preventDefault();

                var p_code = $('#p_code').val();

                $.ajax({
                    type:'POST',
                    url:'{% url "users:user_add_project" %}',
                    data: {
                        'project_code': p_code,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function(response){
                        console.log(response);
                        if(response.is_valid) {
                            window.location.href='/user/dashboard'
                        }
                        else {
                            if(response.errors.project_code) {
                                $('#code-error').empty()
                                var project_code_error = "<span style='color:red'>"+response.errors.project_code+"</span>"
                                $('#code-error').append(project_code_error)
                            }
                            else {
                                $('#code-error').empty()
                            }
                        }
                    }

                });
            });
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

users/templates/userreg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>reCon User Registration</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg custom-navbar" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">reCon</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Register
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="/contractor/register">Contractor</a></li>
                            <li><a class="dropdown-item" href="/user/register">Client</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/login">Login</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container text-center my-5">
        <h3>Client Registration</h3>
    </div>
    <div class="container d-flex flex-column flex-md-row pb-5">
        <div class="container w-75">
            <h4 class="my-3">Registration</h3>
        
            <form id="register" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <label class="form-label">First Name:</label>
                    <input class="form-control" type="text" name="fname" id="r_fname"/>
                    <div id="fname-error"></div>
                </div>
                <div class="mb-3">
                    <label class="form-label">Last Name:</label>
                    <input class="form-control" type="text" name="lname" id="r_lname"/>
                    <div id="lname-error"></div>
                </div>
                <div class="mb-3">
                    <label class="form-label">Email:</label>
                    <input class="form-control" type="email" name="email" id="r_email"/>
                    <div id="email-error"></div>
                </div>
                <div class="mb-3">
                    <label class="form-label">Password:</label>
                    <input class="form-control" type="password" name="password" id="r_password">
                    <div id="password-error"></div>
                </div>
                <div class="mb-3">
                    <label class="form-label">Confirm Password:</label>
                    <input class="form-control" type="password" name="cpassword" id="c_password">
                    <div id="cpassword-error"></div>
                </div>
                <div class="mb-3 d-flex justify-content-between">
                    <a href="/login" class="btn btn-danger">Cancel</a>
                    <input type="submit" value="Register" class="btn btn-success"/>
                </div>
            </form>
        </div>
    </div>
    <footer class="footer">
        <p>By Jorge Jason Joaquino</p>
    </footer>
    <script>
        $(document).ready(function() {
            $('#register').on('submit', function(e){
                e.preventDefault();

                var f_name = $('#r_fname').val();
                var l_name = $('#r_lname').val();
                var r_email = $('#r_email').val();
                var r_password = $('#r_password').val();
                var c_password = $('#c_password').val();

                $.ajax({
                    type:'POST',
                    url:'{% url "users:user_process" %}',
                    data: {
                        'fname': f_name,
                        'lname': l_name,
                        'email': r_email,
                        'password': r_password,
                        'cpassword': c_password,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function(response){
                        if(response.is_valid) {
                            window.location.href='/user/dashboard';
                        }
                        else {
                            if(response.errors.fname) {
                                $('#fname-error').empty()
                                var fname_error = "<ul>" +
                                "<li style='color:red'>"+response.errors.fname+"</li>" +
                                "</ul>"
                                $('#fname-error').append(fname_error)
                            }
                            else {
                                $('#fname-error').empty()
                            }
                            if(response.errors.lname) {
                                $('#lname-error').empty()
                                var lname_error = "<ul>" +
                                "<li style='color:red'>"+response.errors.lname+"</li>" +
                                "</ul>"
                                $('#lname-error').append(lname_error)
                            }
                            else {
                                $('#lname-error').empty()
                            }
                            if(response.errors.email) {
                                $('#email-error').empty()
                                var email_error = "<ul>" +
                                "<li style='color:red'>"+response.errors.email+"</li>" +
                                "</ul>"
                                $('#email-error').append(email_error)
                            }
                            else {
                                $('#email-error').empty()
                            }
                            if(response.errors.password) {
                                $('#password-error').empty()
                                var password_error = "<ul>" +
                                "<li style='color:red'>"+response.errors.password+"</li>" +
                                "</ul>"
                                $('#password-error').append(password_error)
                            }
                            else {
                                $('#password-error').empty()
                            }
                            if(response.errors.cpassword) {
                                $('#cpassword-error').empty()
                                var cpassword_error = "<ul>" +
                                "<li style='color:red'>"+response.errors.cpassword+"</li>" +
                                "</ul>"
                                $('#cpassword-error').append(cpassword_error)
                            }
                            else {
                                $('#cpassword-error').empty()
                            }
                        }
                    }
                });
            });
        });  
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>