contractors/urls.py
from django.urls import path
from contractors import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "contractors"
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_page, name='login_page'),
    path('login/process', views.login_process, name='login_process'),
    path('contractor/register', views.contractor_registration, name='contractor_register'),
    path('contractor/register/process', views.contractor_process, name='contractor_process'),
    path('contractor/profile/<int:contractor_id>', views.contractor_profile, name="contractor_profile"),
    path('contractor/profile/<int:contractor_id>/upload', views.upload_contractor_image, name="upload_contractor_image"),
    path('images/contractor/<int:image_id>/delete', views.delete_contractor_image, name="delete_contractor_image"),
    path('contractor/profile/<int:contractor_id>/edit', views.edit_profile, name="edit_profile"),
    path('contractor/profile/<int:contractor_id>/edit/process', views.edit_profile_process, name="edit_profile_process"),
    path('contractor/profile/<int:contractor_id>/remove_logo', views.delete_contractor_logo, name="delete_contractor_logo"),
    path('contractor/dashboard', views.contractor_dashboard, name='contractor_dashboard'),
    path('contractor/projects/create', views.create_project, name="create_project"),
    path('contractor/projects/create/process', views.create_process, name="create_process"),
    path('contractor/projects/<int:project_id>', views.show_project, name="show_project"),
    path('contractor/projects/<int:project_id>/upload', views.upload_project_image, name="upload_project_image"),
    path('images/<int:image_id>/delete', views.delete_image, name="delete_project_image"),
    path('contractor/projects/<int:project_id>/edit', views.edit_project, name="edit_project"),
    path('contractor/projects/<int:project_id>/edit/process', views.edit_process, name="edit_process"),
    path('contractor/projects/<int:project_id>/createUpdate', views.create_update, name="create_update"),
    path('contractor/projects/<int:project_id>/createUpdate/process', views.update_process, name="update_process"),
    path('contractor/projects/<int:project_id>/updates/<int:update_id>', views.show_update, name="show_update"),
    path('contractor/projects/<int:project_id>/updates/<int:update_id>/upload', views.upload_update_image, name="upload_update_image"),
    path('images/updates/<int:image_id>/delete', views.delete_update_image, name="delete_update_image"),
    path('contractor/projects/<int:project_id>/updates/<int:update_id>/edit', views.edit_update, name="edit_update"),
    path('contractor/projects/<int:project_id>/updates/<int:update_id>/edit/process', views.edit_update_process, name="edit_update_process"),
    path('contractor/projects/<int:project_id>/updates/<int:update_id>/delete', views.delete_update, name="delete_update"),
    path('contractor/projects/<int:project_id>/delete', views.delete_project, name="delete_project"),
    path('logout', views.logout, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recon/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('contractors.urls')),
    path('user/', include('users.urls')),
]

contractors/models.py
from django.db import models
from django.conf import settings
from users.models import User

import re
import random
import string
import os

from decimal import Decimal
from datetime import datetime

# Create your models here.

class ContractorManager(models.Manager):

    def validator(self, postData, instance=None):
        errors = {}

        email_regex = re.compile(r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$')
        mobile_regex =re.compile(r'(\+?\d{2}?\s?\d{3}\s?\d{3}\s?\d{4})|([0]\d{3}\s?\d{3}\s?\d{4})')

        if len(postData['company_name']) < 2:
            errors['company_name'] = "Company Name is required and should be at least 2 characters."

        if not email_regex.match(postData['email']):
            errors['email'] = "Please enter a valid email address."
        elif instance is None and (self.filter(email=postData['email']).exists() or User.objects.filter(email=postData['email']).exists()):
            errors['email'] = "Email is already in use."
        elif instance is not None and (self.filter(email=postData['email']).exclude(id=instance.id).exists() or User.objects.filter(email=postData['email']).exists()):
            errors['email'] = "Email is already in use."

        if len(postData['specialization']) < 3:
            errors['specialization'] = "Specialization is required and should be at least 3 characters"

        if not mobile_regex.match(postData['mobile']):
            errors['mobile'] = "Please enter a valid mobile phone number."

        if 'password' in postData:
            if len(postData['password']) < 8:
                errors['password'] = "Password should be at least 8 characters."

            if postData['password'] != postData['cpassword']:
                errors['cpassword'] = "Passwords do not match."

        return errors

class Contractor(models.Model):
    company_name = models.CharField(max_length=45)
    email = models.EmailField(max_length=255, unique=True)
    specialization = models.CharField(max_length=45)
    mobile = models.CharField(max_length=20)
    landline = models.CharField(max_length=20, null=True, blank=True)
    password = models.CharField(max_length=128)
    is_contractor = models.BooleanField(default=True)
    company_description = models.TextField(null=True, blank=True, default="")
    logo = models.ImageField(upload_to="logos/",null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ContractorManager()

    def remove_logo(self):
        os.remove(os.path.join(settings.MEDIA_ROOT, self.logo.path))
        self.logo = None
        self.save()


class ProjectManager(models.Manager):
    def validator(self, postData, instance=None):
        errors = {}

        decimal_regex = re.compile('^[0-9]+(\.[0-9]+)?$')
        if len(postData['project_name']) < 2:
            errors['project_name'] = "Project Name is required and should be at least 2 characters."
        elif instance is None and self.filter(project_name=postData['project_name']).exists():
            errors['project_name'] = "Project Name already exists."
        elif instance is not None and self.filter(project_name=postData['project_name']).exclude(id=instance.id).exists():
            errors['project_name'] = "Project Name already exists."

        if len(postData['project_description']):
            if len(postData['project_description']) < 10:
                errors['project_description'] = "Project Description should be at least 10 characters."
        
        if not postData['project_cost']:
            errors['project_cost'] = "Please input a valid cost."
        elif not decimal_regex.match(postData['project_cost']):
            errors['project_cost'] = "Please input a valid cost."
        elif Decimal(postData['project_cost']) < 0:
            errors['project_cost'] = "Please input a valid cost."

        try:
            completion_date = datetime.strptime(postData['completion_date'], '%Y-%m-%d').date()
            if completion_date <= datetime.now().date():
                errors['completion_date'] = "Completion date must not be in the past."
        except ValueError:
            errors['completion_date'] = "Please include a valid date."
        return errors
    
    def create(self, **kwargs):
        if 'project_code' not in kwargs:
            kwargs['project_code'] = ''.join(random.choices(string.ascii_uppercase + string.digits, k=5))

        return super().create(**kwargs)


class Project(models.Model):
    contractor = models.ForeignKey(Contractor, related_name='projects', on_delete=models.CASCADE)
    owners = models.ManyToManyField(User, related_name='projects')
    project_name = models.CharField(max_length=45)
    project_description = models.TextField()
    project_cost = models.DecimalField(max_digits=10, decimal_places=2)
    project_code = models.CharField(max_length=5, unique=True, default="")
    completion_date = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ProjectManager()


class UpdateManager(models.Manager):
    def validator(self, postData, instance=None):
        errors = {}

        if len(postData['update_description']) < 10:
            errors['update_description'] = "Description is required and should be at least 10 characters."

        try:
            date = datetime.strptime(postData['date'], '%Y-%m-%d').date()
            if date > datetime.now().date():
                errors['date'] = "Date of update must not be in the future."
        except ValueError:
            errors['date'] = "Invalid date format."
        return errors

class Update(models.Model):
    project = models.ForeignKey(Project, related_name="updates", on_delete=models.CASCADE)
    update_description = models.TextField()
    date = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UpdateManager()

class Photos(models.Model):
    contractor = models.ForeignKey(Contractor, related_name="photos", on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, related_name='photos', on_delete=models.CASCADE, null=True)
    update = models.ForeignKey(Update, related_name='photos', on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='photos/')
    caption = models.TextField(null=True)

    def delete(self, *args, **kwargs):
        if self.image:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.image.path))

        super(Photos, self).delete(*args, **kwargs)

contractors/templates/conreg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contractor Registration</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg custom-navbar" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">reCon</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Register
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="/contractor/register">Contractor</a></li>
                            <li><a class="dropdown-item" href="/user/register">Client</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/login">Login</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container text-center my-5">
        <h3>Contractor Registration</h3>
    </div>
    <div class="container d-flex flex-column flex-md-row pb-5">
        <div class="container w-75">
            <h4 class="my-3">Registration</h4>
        
            <form class="row g-3" id="register" method="POST">
                {% csrf_token %}
                <input type="hidden" name="is_contractor" id="r_is_contractor" value="True">
                <div class="">
                    <label class="form-label">Company Name:</label>
                    <input class="form-control" type="text" name="company_name" id="r_company_name"/>
                    <div class="error-message" id="company_name-error"></div>
                </div>
                <div class="">
                    <label class="form-label">Specialization:</label>
                    <input class="form-control" type="text" name="specialization" id="r_specialization"/>
                    <div class="error-message" id="specialization-error"></div>
                </div>
                <div class="col-md-6">
                    <label class="form-label">Email:</label>
                    <input class="form-control" type="email" name="email" id="r_email"/>
                    <div class="error-message" id="email-error"></div>
                </div>
                <div class="col-md-6">
                    <label class="form-label">Mobile Number:</label>
                    <input class="form-control" type="text" name="mobile" id="r_mobile"/>
                    <div class="error-message" id="mobile-error"></div>
                </div>
                <div class="">
                    <label class="form-label">Password:</label>
                    <input class="form-control" type="password" name="password" id="r_password">
                    <div class="error-message" id="password-error"></div>
                </div>
                <div class="mb-3">
                    <label class="form-label">Confirm Password:</label>
                    <input class="form-control" type="password" name="cpassword" id="c_password">
                    <div class="error-message" id="cpassword-error"></div>
                </div>
                <div class="mb-3 d-flex justify-content-between">
                    <a href="/login" class="btn btn-danger">Cancel</a>
                    <input type="submit" value="Register" class="btn btn-success"/>
                </div>
            </form>
        </div>
    </div>
    <footer class="footer">
        <p>By Jorge Jason Joaquino</p>
    </footer>

    <script>
        $(document).ready(function() {
            $('#register').on('submit', function(e){
                e.preventDefault();

                var c_name = $('#r_company_name').val();
                var r_specialization = $('#r_specialization').val();
                var r_mobile = $('#r_mobile').val();
                var r_email = $('#r_email').val();
                var r_password = $('#r_password').val();
                var c_password = $('#c_password').val();

                $.ajax({
                    type:'POST',
                    url:'{% url "contractors:contractor_process" %}',
                    data: {
                        'company_name': c_name,
                        'specialization': r_specialization,
                        'mobile': r_mobile,
                        'email': r_email,
                        'password': r_password,
                        'cpassword': c_password,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function(response){
                        console.log(response);
                        if(response.is_valid) {
                            window.location.href='/contractor/dashboard';
                        }
                        else {
                            $('.error-message').empty();
                            for (oneError in response.errors) {
                                console.log(oneError)
                                console.log(response.errors[oneError])
                                if(response.errors.hasOwnProperty(oneError)) {
                                    var error_message = "<ul>" +
                                    "<li style='color:red'>" + response.errors[oneError] + "</li>" +
                                    "</ul>"
                                    $('#' + oneError + '-error').append(error_message)
                                }
                            }
                        }
                    }
                });
            });
        });
    </script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

contractors/templates/createProj.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>reCon Create Project</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg custom-navbar" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/contractor/dashboard">reCon</a>
            <span class="navbar-text">{{contractor.company_name}}</span>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/contractor/dashboard">Dashboard</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Profile
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="/contractor/profile/{{contractor.id}}">View Profile</a></li>
                            <li><a class="dropdown-item" href="/contractor/profile/{{contractor.id}}/edit">Edit Profile</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active fw-bold" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Projects
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="/contractor/register">Create Project</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/logout">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container text-center my-5">
        <h3>Create Project</h3>
    </div>
    <div class="container d-flex flex-column flex-md-row pb-5">
        <div class="container w-75">
            <form id="create" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <label class="form-label">Project Name:</label>
                    <input class="form-control" type="text" name="project_name" id="r_project_name"/>
                    <div class="error-message" id="project_name-error"></div>
                </div>
                <div class="mb-3">
                    <label class="form-label">Description:</label>
                    <textarea class="form-control" type="text" name="project_description" id="r_project_description"></textarea>
                    <div class="error-message" id="project_description-error"></div>
                </div>
                <div class="mb-3">
                    <label class="form-label">Project Cost:</label>
                    <input class="form-control" type="text" name="project_cost" id="r_project_cost"/>
                    <div class="error-message" id="project_cost-error"></div>
                </div>
                <div class="mb-3">
                    <label class="form-label">Target Completion Date:</label>
                    <input class="form-control" type="date" name="completion_date" id="r_completion_date"/>
                    <div class="error-message" id="completion_date-error"></div>
                </div>
                <div class="mb-3 d-flex justify-content-between">
                    <a href="/contractor/dashboard" class="btn btn-danger">Cancel</a>
                    <input type="submit" value="Create Project" class="btn btn-success"/>
                </div>
            </form>
        </div>
    </div>
    <footer class="footer">
        <p>By Jorge Jason Joaquino</p>
    </footer>
    <!-- AJAX -->
    <script>
        $(document).ready(function() {
            $('#create').on('submit', function(e){
                e.preventDefault();

                var p_name = $('#r_project_name').val();
                var p_description = $('#r_project_description').val();
                var p_cost = $('#r_project_cost').val();
                var p_date = $('#r_completion_date').val();

                $.ajax({
                    type:'POST',
                    url:'{% url "contractors:create_process" %}',
                    data: {
                        'project_name': p_name,
                        'project_description': p_description,
                        'project_cost': p_cost,
                        'completion_date': p_date,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function(response){
                        console.log(response);
                        if(response.is_valid) {
                            window.location.href='/contractor/dashboard';
                        }
                        else {
                            $('.error-message').empty();
                            for (oneError in response.errors) {
                                console.log(oneError)
                                console.log(response.errors[oneError])
                                if(response.errors.hasOwnProperty(oneError)) {
                                    var error_message = "<ul>" +
                                    "<li style='color:red'>" + response.errors[oneError] + "</li>" +
                                    "</ul>"
                                    $('#' + oneError + '-error').append(error_message)
                                }
                            }
                        }
                    }

                });
            });
        });
    </script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

contractors/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>reCon Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg custom-navbar" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">reCon</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Register
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="/contractor/register">Contractor</a></li>
                            <li><a class="dropdown-item" href="/user/register">Client</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/login">Login</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid mt-5 pb-5">
        <div class="text-center my-5">
            <h1>reCon</h1>
        </div>
        <div class="d-flex flex-column flex-md-row pb-5">
            <div class="container">
                <h3 class="my-3">Not yet registered?</h3>
                <div class="d-flex flex-row flex-md-column">
                    <div class="mb-3 me-3">
                        <a href="/contractor/register" class="btn btn-primary btn-lg"><h4>Contractor</h4></a>
                    </div>
                    <div class="mb-3">
                        <a href="/user/register" class="btn btn-primary btn-lg"><h4>Client</h4></a>
                    </div>
                </div>
            </div>
            <div class="container">
                <h3 class="my-3">Login</h3>
                
                <form id="login" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label class="form-label">Email</label>
                        <input class="form-control" type="email" name="email" id="id_email"/>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Password:</label>
                        <input class="form-control" type="password" name="password"
                        id="id_password"/>
                    </div>
                    <div id="login-error" class="mb-3"></div>
                    <div class="mb-3">
                        <input type="submit" value="Login" class="btn btn-primary"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <footer class="footer">
        <p>By Jorge Jason Joaquino</p>
    </footer>

    <script>
        $(document).ready(function() {
            $('#login').on('submit', function(e) {
                e.preventDefault();

                var email = $('#id_email').val();
                var password = $('#id_password').val();

                $.ajax({
                    type:'POST',
                    url:'{% url "contractors:login_process" %}',
                    data: {
                        'email': email,
                        'password': password,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function(response){
                        if(response.is_valid && response.is_contractor) {
                            window.location.href='/contractor/dashboard';
                        }
                        else if (response.is_valid && !response.is_contractor) {
                            window.location.href='/user/dashboard'
                        } 
                        else {
                            $('#login-error').empty()
                            var error = "<ul>" +
                                "<li style='color:red'>Invalid Email or Password</li>" +
                                "</ul>"
                            $('#login-error').append(error);

                        }
                    }
                });
            });
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>